INSERT INTO CLIENTE SELECT CPF, NOME, ENDERECO_1 AS ENDERECO,BAIRRO,CIDADE,ESTADO,CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,IDADE,GENERO, LIMITE_DE_CREDITO AS LIMITE_CREDITO,VOLUME_DE_COMPRA AS VOLUME_COMPRA,PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES ;


SELECT * FROM CLIENTE;