SELECT * FROM TABELA_DE_PRODUTOS ;
USE SUCOS_FRUTAS
SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

INSERT INTO PRODUTOS SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

SELECT * FROM PRODUTOS;


INSERT INTO PRODUTOS SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA AS PRECO_LISTA 
FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO <> '1040107';


INSERT INTO CLIENTES SELECT CPF, NOME, ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,,DATA_NASCIMENTO,IDADE,GENERO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA