SELECT INF.CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE, P.NOME_DO_PRODUTO
FROM ITENS_NOTAS_FISCAIS INF 
INNER JOIN TABELA_DE_PRODUTOS P
ON INF.CODIGO_DO_PRODUTO = P.CODIGO_DO_PRODUTO
GROUP BY  P.NOME_DO_PRODUTO, INF.CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;