SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES --> Somente 7 clientes possuem em seus bairros vendedores
SELECT COUNT(*) FROM TABELA_DE_VENDEDORES; 
-- 4 VENDEDORES

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC 
INNER JOIN 
TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;

-- QUAL VENDEDOR QUE NÃO TEM CLIENTE NO SEU BAIRRO ?? R: ROBERTA MARTINS EM COPACABANA

SELECT DISTINCT 
TV.NOME AS NOME_DO_VENDEDOR, 
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE, 
TC.NOME AS NOME_DO_CLIENTE 
FROM TABELA_DE_CLIENTES TC 
RIGHT JOIN TABELA_DE_VENDEDORES TV 
ON TC.BAIRRO = TV.BAIRRO;