USE SUCOS_FRUTAS;
SELECT 
TC.CPF AS CPF_DO_CADASTRO, TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

SELECT DISTINCT 
TC.CPF AS CPF_CADASTRO,TC.NOME AS NOME_DO_CLIENTE, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
INNER JOIN  NOTAS_FISCAIS NF ON TC.CPF = NF.CPF;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

INSERT INTO TABELA_DE_CLIENTES
(CPF,NOME,ENDERECO_1, ENDERECO_2,BAIRRO,CIDADE,ESTADO,CEP,DATA_DE_NASCIMENTO,IDADE,GENERO,LIMITE_DE_CREDITO,VOLUME_DE_COMPRA,PRIMEIRA_COMPRA)
VALUES('23412632331', 'Juliana Silva', 'Rua Tramandaí', ' ', 'Bangu', 'Rio de
Janeiro', 'RJ', '23400000', '1989-02-04', 33, 'F', '180000', '24500', 0); 

SELECT DISTINCT 
TC.CPF AS CPF_DO_CADASTRO,
TC.NOME AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF 
ON TC.CPF = NF.CPF 
WHERE NF.CPF IS NULL;