SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES; 

SELECT * FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN ('Copacabana','Jardins','Santo Amaro','Tijuca'); 

SELECT * FROM TABELA_DE_CLIENTES 
WHERE BAIRRO IN 
(SELECT DISTINCT BAIRRO 
FROM TABELA_DE_VENDEDORES);