use SUCOS_FRUTAS;
SELECT * 
FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE 
FROM TABELA_DE_CLIENTES;

SELECT CIDADE,IDADE
FROM TABELA_DE_CLIENTES
ORDER BY CIDADE,IDADE;

SELECT CIDADE,
SUM(IDADE) AS IDADE 
FROM TABELA_DE_CLIENTES 
GROUP BY CIDADE;

SELECT CIDADE, SUM(IDADE) AS IDADE,
SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE; 

SELECT CIDADE,AVG(IDADE) AS IDADE,
SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE,COUNT(*) AS NUMERO_DE_CLIENTES
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS 
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja' 
GROUP BY EMBALAGEM;