SELECT NOME, 
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Cliente Grande'
WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO > 110000 THEN 'Cliente Médio'
ELSE 'Cliente Pequeno' END ) AS CLASSIFICACAO_CLIENTE
FROM TABELA_DE_CLIENTES
ORDER BY (CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Cliente Grande'
WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO > 110000 THEN 'Cliente Médio'
ELSE 'Cliente Pequeno' END );
