SELECT * 
FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES 
GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO 
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;

SELECT EMBALAGEM, 
MAX(PRECO_DE_LISTA) AS PRECO_MAX, 
MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, 
MAX(PRECO_DE_LISTA) AS PRECO_MAX,
MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10 
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >= 20;