 CREATE TABLE CLIENTE (
 CPF VARCHAR(11) NOT NULL,
 PRIMARY KEY (CPF),
 NOME VARCHAR(100)  NULL,
 ENDERECO VARCHAR(150)  NULL,
 BAIRRO VARCHAR(50) NULL,
 CIDADE VARCHAR(50)  NULL,
 ESTADO VARCHAR(50)  NULL,
 CEP VARCHAR(8)  NULL,
 DATA_NASCIMENTO DATE  NULL,
 IDADE INTEGER NULL,
 GENERO VARCHAR (1) NULL,
 LIMITE_CREDITO FLOAT,
 VOLUME_COMPRA FLOAT,
 PRIMEIRA_COMPRA BIT

 );