CREATE TABLE ITENS_VENDIDOS(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
QUANTIDADE INTEGER NULL,
PRECO FLOAT NULL,
PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE ITENS_VENDIDOS
ADD CONSTRAINT FK_TABELA_DE_VENDAS 
FOREIGN KEy (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);

ALTER TABLE ITENS_VENDIDOS
ADD CONSTRAINT FK_PRODUTOS 
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);