CREATE TABLE TABELA_DE_VENDAS (
NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR (11) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO)
); 
DROP TABLE VENDAS;

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT  FK_CLIENTE 
FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_VENDEDORES 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA);

ALTER TABLE TABELA_DE_VENDAS 
ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL;