SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' OR TAMANHO = '470 ml'; 

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE NOT(SABOR = 'Manga' OR TAMANHO = '470 ml');

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE NOT(SABOR = 'Manga' AND TAMANHO = '470 ml'); 

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE NOT SABOR  = 'Manga' AND TAMANHO = '470 ml';

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE SABOR in ('Manga', 'LARANJA','MELANCIA');

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('MANGA','LARANJA','MELANCIA') AND TAMANHO ='1 LITRO';

SELECT * 
FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('rio de janeiro','Sao paulo');

SELECT * 
FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('RIO DE JANEIRO','SAO PAULO') AND (IDADE >= 20 AND IDADE <= 25);