SELECT * 
FROM TABELA_DE_CLIENTES; 

SELECT * 
FROM TABELA_DE_CLIENTES
WHERE IDADE > 20;

SELECT * 
FROM TABELA_DE_CLIENTES
WHERE IDADE <= 20;

SELECT * 
FROM TABELA_DE_CLIENTES
WHERE IDADE <> 18; 

SELECT *
FROM TABELA_DE_CLIENTES --AAAA-MM-DD
WHERE DATA_DE_NASCIMENTO >= '1995-11-14';

SELECT * 
FROM TABELA_DE_CLIENTES 
WHERE BAIRRO >= 'Lapa'; 