SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('LIMA/LIMAO','MORANGO/LIMAO'); 

SELECT * 
FROM TABELA_DE_PRODUTOS 
WHERE SABOR LIKE '%LIMAO';

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%MACA%';

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE 'MORANGO%';

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE (SABOR LIKE 'MORANGO%') AND (EMBALAGEM = 'PET');
