SELECT * 
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA ;

SELECT *
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC;

SELECT * 
FROM TABELA_DE_PRODUTOS
ORDER BY EMBALAGEM,NOME_DO_PRODUTO;

SELECT * 
FROM TABELA_DE_PRODUTOS 
ORDER BY EMBALAGEM DESC,NOME_DO_PRODUTO DESC;

