SELECT * FROM TABELA_DE_CLIENTES; 

SELECT NOME, LOWER(NOME) AS NOME_MINUSCULO , UPPER(NOME) AS NOME_MAIUSCULO FROM TABELA_DE_CLIENTES;

SELECT NOME, CONCAT(ENDERECO_1,' ',BAIRRO, ' ', CIDADE,' ',ESTADO,' - ', CEP) AS ENDERECO_COMPLETO 
FROM TABELA_DE_CLIENTES;

SELECT NOME, ENDERECO_1 + ' ' + BAIRRO + ' ' + CIDADE + ' ' + ESTADO + ' - ' + CEP AS ENDERECO_COMPLETO 
FROM TABELA_DE_CLIENTES; 

SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO, 3) AS TRES_PRIMEIROS_CHAR 
FROM TABELA_DE_PRODUTOS;

SELECT TAMANHO, REPLACE(TAMANHO, 'Litros', 'L') AS TAMANHO_MODIFICADO 
FROM TABELA_DE_PRODUTOS;

SELECT TAMANHO, REPLACE((REPLACE(TAMANHO, 'Litros', 'L')), 'Litro', 'L') AS TAMANHO_MODIFICADO 
FROM TABELA_DE_PRODUTOS;