SELECT GETDATE() AS DATA_ATUAL; 

SELECT GETDATE() AS DIA_ATUAL ,
DATEADD(DAY,10,GETDATE()) AS DAQUI_A_10DIAS;

SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY,10,GETDATE()) AS DATA_DAQUI_10_DIAS,
DATEADD(DAY, -48,GETDATE()) AS DATA_48_DIAS_ATRAS,DATEDIFF (HOUR, '2025-01-01',GETDATE()) AS HORAS_DESDE_INICIO;


SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY,10,GETDATE()) AS DATA_DAQUI_10_DIAS,
DATEADD(DAY, -48,GETDATE()) AS DATA_48_DIAS_ATRAS,DATEDIFF (DAY, '2025-01-01',GETDATE()) AS DIAS_DESDE_INICIO;

