SELECT * FROM PRODUTOS;

UPDATE PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1040107';

SELECT * FROM PRODUTOS WHERE SABOR = 'Manga';

UPDATE PRODUTOS 
SET PRECO_LISTA = PRECO_LISTA * 1.10
WHERE SABOR = 'Manga';

SELECT DESCRITOR 
FROM PRODUTOS 
WHERE TAMANHO = '350 ml';

SELECT DESCRITOR,
replace(DESCRITOR, '350 ml', '550 ml')
FROM PRODUTOS 
WHERE TAMANHO = '350 ml';

UPDATE PRODUTOS 
SET DESCRITOR = REPLACE (DESCRITOR, '350 ml', '550 ml'), TAMANHO = '550 ml'
WHERE TAMANHO = '350 ml';

SELECT *
FROM PRODUTOS 
WHERE TAMANHO = '550 ml';