SELECT [NOME], [PERCENTUAL COMISSÃO]
FROM [TABELA DE VENDEDORES] 
WHERE [PERCENTUAL COMISSÃO] <= 0.08;

SELECT [NOME DO PRODUTO],[EMBALAGEM],[PRECO DE LISTA] AS [ValorProduto]
FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] < 6.0 AND [EMBALAGEM] = 'Lata';

SELECT [NOME],[ESTADO]
FROM [TABELA DE CLIENTES]
WHERE NOT( [ESTADO] = 'SP' OR [ESTADO] = 'RJ');