SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] > 7.0;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [EMBALAGEM] <= 'Lata';

SELECT DISTINCT [EMBALAGEM]
FROM [TABELA DE PRODUTOS];

SELECT [NOME],[DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE [DATA DE NASCIMENTO] > '1995-12-31';

SELECT [NOME],[DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
WHERE YEAR([DATA DE NASCIMENTO]) > '1995';