SELECT [NOME], [BAIRRO]
FROM [TABELA DE CLIENTES]
WHERE [BAIRRO] = 'Copacabana' or [BAIRRO] = 'Tijuca';

SELECT [NOME], [ESTADO], [PRIMEIRA COMPRA]
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1 AND [ESTADO] = 'SP';