CREATE TABLE TAB_IDENTITY 
(ID INT IDENTITY(1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL); 

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE X');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Y');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE Z');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE W');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A');

SELECT * FROM TAB_IDENTITY; 

DELETE FROM TAB_IDENTITY 
WHERE ID = 1;

SELECT * FROM TAB_IDENTITY; 

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE B');

SELECT * FROM TAB_IDENTITY; 

DELETE FROM TAB_IDENTITY 
WHERE ID = 6;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE C');
SELECT * FROM TAB_IDENTITY; 

CREATE TABLE TAB_IDENTITY2 
(ID INT IDENTITY(100,5) NOT NULL,
DESCRITOR VARCHAR(20) NULL); 

INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE Y');
INSERT INTO TAB_IDENTITY2 (DESCRITOR) VALUES ('CLIENTE Z');

SELECT * FROM TAB_IDENTITY2; 

SELECT * FROM TAB_IDENTITY;
DELETE FROM TAB_IDENTITY
WHERE ID < 7  ;