USE [VENDAS SUCOS]

CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL,
TOTAL_VENDA FLOAT);

SELECT 
TV.DATA_VENDA,
SUM(TIV.QUANTIDADE  * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV
INNER JOIN ITENS_VENDIDOS TIV
ON TV.NUMERO = TIV.NUMERO
GROUP BY
TV.DATA_VENDA;

SELECT * FROM CLIENTE

INSERT INTO TABELA_DE_VENDAS
VALUES('0100','2018-05-15','1471156710','235',0.18);

INSERT INTO ITENS_VENDIDOS
VALUES ('0100','1000889',100,10);

SELECT * FROM TAB_FATURAMENTO;


INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA; 

DROP TABLE TAB_FATURAMENTO;

CREATE TABLE TAB_FATURAMENTO (
    DATA_VENDA DATE NULL, 
    TOTAL_VENDA FLOAT
);

SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0100', '2018-05-15', '1471156710', '235', 0.18
); 

DELETE FROM TABELA_DE_VENDAS 
WHERE NUMERO = '0100'

SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0101', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO ITENS_VENDIDOS 
VALUES (
    '0101', '1000889', 100, 10
);

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0102', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO ITENS_VENDIDOS 
VALUES (
    '0102', '1000889', 100, 10
);

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0103', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO ITENS_VENDIDOS 
VALUES (
    '0103', '1000889', 100, 10
);

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0104', '2018-05-16', '1471156710', '235', 0.18
);

INSERT INTO ITENS_VENDIDOS 
VALUES (
    '0104', '1000889', 100, 10
);

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;
